spring:
  application:
    name: "Fullstack Assignment (Kotlin)"
  datasource:
    url: jdbc:mariadb://localhost:53306/assignment
    username: root
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl